# Cloudflare Pages configuration
name = "osrs-flip-tracker-combined"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables (set these in Cloudflare dashboard)
# DISCORD_WEBHOOK_URL - for feedback API
# VITE_* variables - for build-time injection